Navigation Review
olaassem/Florence pull request #3
Opened 2018-10-02 17:37 UTC by olaassem

Since I was committing all my updates to the header branch, updates to the navigation (e.g font-size) is captured now in the (later commits) now breakout branches.   

Apologies for that.

The expanding menu will be implemented at a later stage once the full layout is in place.

Thanks!!!

2018-10-03 17:25 UTC, mzlock requested changes
Sorry, but quite a few changes here. 😅 

You use flexbox a lot. It's great that you know how to work with it and are comfortable with it. But, I thiiiink you're coming to lean on it too much where other approaches might be more efficient. At least for your wrappers, I'd love to see you use auto margins to get those to center.

2018-10-03 17:25 UTC, mzlock commented on public/index.html
> +<section id="problem-section" class="problem">
indentation!

2018-10-03 17:25 UTC, mzlock commented on public/index.html
> +        <a href="http://www.who.int/" target="_blank"><sup class="problem__sup">2</sup></a>
Reverse these so that they're `<sup><a></a></sup>`

2018-10-03 17:25 UTC, mzlock commented on public/index.html
> +    <a class="footer__link" href="https://www.viget.com/contact/" target="_blank">Contact Us</a>
The `<sup>` links kinda make sense to open in a new tab, but I don't think this one does... just a usability note

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/abstracts/_mixins.scss
> +  bottom: $btm;
why might you be positioning from the `bottom` and not the `top`? Nothing wrong with that, really, I just always go for `top` and `left`

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/base/_typography.scss
> +  letter-spacing: .05em;
🔤

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/base/_typography.scss
> +    }
once you reverse those `<sup>` and `<a>` tags, you may need to move these styles around a bit. And make sure the hover state is on the links

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/base/_typography.scss
> +    }
delete this since it's not doing anything??

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/base/_typography.scss
> +    line-height: 2.2rem;
🔤

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/base/_typography.scss
> +    font-style: normal;
🔤

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/layouts/_header.scss
> +  width: 100vw;
Do you need this? The header should be full width by default

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/layouts/_header.scss
> +    margin: 4rem 0rem 1.5rem;
ooooh, interesting. You're using flexbox to center things rather than a `margin-left: auto; margin-right: auto;`. 

While the flexbox approach works, I think using an auto margin approach would require less lines of CSS on your `.header` and maybe in a couple of other spots.

Flexbox seems to be your go-to! But maybe save it for spots where content needs to flex more. Using good old margins will prooobably take less code and will likely save you some cross-browser headaches when we get to testing IE11

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/layouts/_navigation.scss
> +  margin: auto 0;
I think you have this reversed

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/layouts/_navigation.scss
> +  padding: 0rem;
are you overriding some default padding from somewhere?

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/layouts/_navigation.scss
> +  padding: 0rem;
Also - you can just use `padding: 0` (no unit) to remove padding/margins. It's shorter, so we usually do that

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/layouts/_navigation.scss
> +  top: 0;
`position` and `top` are repeated here.

Your build tools will take care of the vendor pre-fixing like `position: -webkit-sticky;`

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/layouts/_navigation.scss
> +  }
🔤

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/layouts/_navigation.scss
> +    z-index: 5;
Try making this (and your other wrappers) centered without flexbox.

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/layouts/_navigation.scss
> +      max-width: 50rem;
why are you waiting to apply the `max-width` in a media query? Does this break anything if applied all the time?

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/layouts/_navigation.scss
> +    justify-content: center;
is this `display: flex`? This property won't do anything unless this element is `display: flex`

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/layouts/_navigation.scss
>  }
is the nav red or the link red? Just questioning the class naming here

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/layouts/_problem.scss
> +  margin-top: 1.5rem;
try centering things without flexbox

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/layouts/_problem.scss
> +    padding: 2.5rem 1.5rem;
🔤

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/layouts/_problem.scss
> +    padding: 2.5rem 1.5rem;
Also - does this need to be flexbox? Or can you achieve this will a little less code??

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/layouts/_problem.scss
> +      // padding: 0rem 1.5rem;
delete?

2018-10-03 17:25 UTC, mzlock commented on src/stylesheets/layouts/_problem.scss
> +      }
You have some repeated styles in the media query here

2018-10-03 20:46 UTC, mzlock commented on public/index.html
> +        <a href="http://www.who.int/" target="_blank"><sup class="problem__sup">2</sup></a>
Resolved in #6

2018-10-04 00:12 UTC, olaassem commented on public/index.html
> +    <a class="footer__link" href="https://www.viget.com/contact/" target="_blank">Contact Us</a>
Resolved in PR #6 :)

2018-10-04 00:13 UTC, olaassem commented on src/stylesheets/abstracts/_mixins.scss
> +  bottom: $btm;
Based on where I want to position an element sometimes. But this is a good way to streamline code!

2018-10-04 00:19 UTC, olaassem commented on src/stylesheets/base/_typography.scss
> +    }
Resolved in PR #6

2018-10-04 00:54 UTC, olaassem commented on src/stylesheets/layouts/_navigation.scss
>  }
nav red. link red as in the sup red? that's orange-red.

2018-10-04 00:54 UTC, olaassem commented on src/stylesheets/layouts/_navigation.scss
> +      max-width: 50rem;
nope. good call.

2018-10-04 00:56 UTC, olaassem commented on src/stylesheets/layouts/_navigation.scss
> +    z-index: 5;
the nav breaks at smaller breakpoints without flex. don't understand why. why does the text wrap with flex and not without?

2018-10-04 14:07 UTC, mzlock commented on src/stylesheets/layouts/_navigation.scss
>  }
oh, it's the `.red-nav` class that I'm finding a bit odd. Not the color naming!

2018-10-09 13:39 UTC, merged